title: "Recherche Reproductible"
author: "Recherche Reproductible"
description: "Un r√©seau national de chercheurs pour la promotion de la recherche reproductible."
email: Nicolas.Rougier@inria.fr
contact: Nicolas.Rougier@inria.fr
show_excerpts: false # set to true to show excerpts on the homepage
future: true

# url: https://fr-rn.github.io/FR-RN
# url: "https://www.french-rn.org/FR-RN"
url: "https://www.recherche-reproductible.fr/"
baseurl: ""

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-scholar

scholar:
  style: acm-siggraph
  locale: en
  sort_by: year, month
  order: descending
  group_by: none
  group_order: ascending
  source: ./_data
  bibliography: network.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
    
