title: French Reproducibility Network
author: French Reproducibility Network
description: A national peer-led consortium for the promotion and dissemination of reproducible research.
email: Nicolas.Rougier@inria.fr
contact: Nicolas.Rougier@inria.fr
show_excerpts: false # set to true to show excerpts on the homepage

url: https://fr-rn.github.io/FR-RN
baseurl: /FR-RN
# url: "https://www.french-rn.org/FR-RN"
# baseurl: "/FR-RN"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-scholar
